# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  hand_Lj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  hand_Rj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  omo_Lj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  omo_Rj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  rest_Lj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  rest_Rj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  rotate_Lj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  rotate_Rj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  shouder_Lj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_Rj:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
