arm_l:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  position_only_ik: True
  solve_type: Speed
  kinematics_solver_attempts: 3
  kinematics_solver_timeout: 0.005
  kinematics_solver_search_resolution: 0.005
  
arm_r:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  position_only_ik: True
  solve_type: Speed 
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3



